### ISSUE TITLE
Need to make custom UI inside plugin settings frame

### ISSUE THREAD

**Issue by backskin** [gravitee-io/gravitee-ui-particles#385]
![image](https://github.com/gravitee-io/gravitee-ui-particles/assets/49398278/19d5b352-cad1-45f6-b738-dcf975dca7ae)
Hello! Does anybody know a clever way to make a customized UI inside this plugin settings window (at APIs/Design tab)? I am already familiar with a schema settings in **schemas/schema-form.json**, but my task requires more manageable interface.
I need to add some custom logic like adding user list of policies with multiple parameters inside one element; searching by excerpt on this list of complicated elements; adding switches and custom buttons with its logic inside list's element.
An example is on the screenshot below
![image](https://github.com/gravitee-io/gravitee-ui-particles/assets/49398278/a69372b2-6cc7-4c35-a34f-6354bff9c7a5)

**Comment by ThibaudAV** [comment]
Hello, 

There is currently no way for a conventional APIM user to customize the UI of a Policy. 
It is only possible to configure a schema-form.json. It will be used to validate the Policy's configuration obj and interpreted to display the UI in the best possible way (although you mustn't be too creative and respect certain rules).

What you're proposing is something I've already thought about, but we've never had a need or request for it from our product team. 

For a less conventional use with the latest version of APIM (> 4.3), it's probably possible to develop a specific component on the APIM console (fork + modification on your side). But I don't recommend it, as it will make your updates more complicated and there's no guarantee that it will still work with future evolutions.
